### ISSUE TITLE
convert_zone fails.

### ISSUE THREAD

**Issue by GeoffAtHome** [manzanotti/geniushub-client#3]
Good to see this being used in HA - but has broken what was previously working for me.

Not sure why some many warning are disabled as these are there for a good reason. To stop crashes like this:

```2019-05-19 15:24:29 ERROR (MainThread) [homeassistant.setup] Error during setup of component geniushub
Traceback (most recent call last):
  File "/home/geoff/home-assistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/home/geoff/home-assistant/homeassistant/components/geniushub/__init__.py", line 50, in async_setup
    await data._client.hub.update()  # pylint: disable=protected-access
  File "/home/geoff/home-assistant/venv/lib/python3.6/site-packages/geniushubclient/__init__.py", line 644, in update
    [_populate_zone(z) for z in await self._get_zones_raw]
  File "/home/geoff/home-assistant/venv/lib/python3.6/site-packages/geniushubclient/__init__.py", line 644, in <listcomp>
    [_populate_zone(z) for z in await self._get_zones_raw]
  File "/home/geoff/home-assistant/venv/lib/python3.6/site-packages/geniushubclient/__init__.py", line 557, in _populate_zone
    zone_dict = self._convert_zone(zone_raw)
  File "/home/geoff/home-assistant/venv/lib/python3.6/site-packages/geniushubclient/__init__.py", line 262, in _convert_zone
    elif setpoint_temp != default_temp:                              # noqa: disable=F821; pylint: disable=used-before-assignment
UnboundLocalError: local variable 'setpoint_temp' referenced before assignment
2019-05-19 15:24:29 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:

 - introduction
 - [geniushub](https://home-assistant.io/components/geniushub/)

Please check your config., notification_id=invalid_config>
2019-05-19 15:24:29 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, message=The following components and platforms could not be set up:
```
Still no time to help on the project but hopefully in July.

**Comment by zxdavb** [comment]
I think this:
```python
# noqa: disable=F821; pylint: disable=used-before-assignment
```
followed by this:
```python
UnboundLocalError: local variable 'setpoint_temp' referenced before assignment
```
says it all!

Obviously my fault - I will have a look & sort it out.

**Comment by zxdavb** [comment]
> but has broken what was previously working for me.

FWIW, a `battery_level` PR has been merged, and a `issues` PR has been submitted.

This particular chunk of code deals with converting a v3 schedule into the v1 JSON schema (i.e. `zone['schema']`)

It would be really helpful if you could send me the result of:
```bash
curl --user ${USERNAME}:${HASH} -X GET http://${HUB_ADDRESS}:1223/v3/zone
```

**Comment by GeoffAtHome** [comment]
<< SNIP >>

Deleted for various reasons...

**Comment by zxdavb** [comment]
OK, all my zones, and most of @GeoffAtHome's Zones have (note that each day starts with `"iTm": -1`):
```
"objTimer": [
{"iDay": 0, "iTm":    -1, "fSP":  6},
{"iDay": 0, "iTm": 57600, "fSP": 21.5},
{"iDay": 0, "iTm": 81000, "fSP":  6},

{"iDay": 1, "iTm":    -1, "fSP":  6},
{"iDay": 1, "iTm": 63000, "fSP": 21.5},
{"iDay": 1, "iTm": 81000, "fSP":  6},

{"iDay": 2, "iTm":    -1, "fSP":  6},
{"iDay": 2, "iTm": 63000, "fSP": 21.5},

...
```
However, I see some of @GeoffAtHome's zones have (here, `fSP` is `True` or `False`):
```
"objTimer": [
{"iDay": 0,"iTm":     0,"fSP": 0},
{"iDay": 1,"iTm":     0,"fSP": 0},
{"iDay": 2,"iTm":     0,"fSP": 0},
{"iDay": 2,"iTm": 24000,"fSP": 1},
{"iDay": 2,"iTm": 25200,"fSP": 0},
{"iDay": 3,"iTm":     0,"fSP": 0},
{"iDay": 3,"iTm": 24000,"fSP": 1},

...
```

**Comment by zxdavb** [comment]
Temporary fix pushed to https://github.com/zxdavb/geniushub-client/tree/v0.4.9

**Comment by zxdavb** [comment]
https://github.com/home-assistant/home-assistant/pull/24022 has been merged.

**Comment by zxdavb** [comment]
@GeoffAtHome A permanent fix has been pushed via https://github.com/zxdavb/geniushub-client/tree/v0.5.01. 

To confirm the fix, I'd need to see your JSON, which you can send me via a PM/email:
```
python ghclient.py ${HUB_ADDRESS} -u ${USERNAME} -p ${PASSWORD} zones -vvv > zones_raw.json
python ghclient.py ${HUB_ADDRESS} -u ${USERNAME} -p ${PASSWORD} devices -vvv > devices_raw.json
```
